### PR TITLE
Add missing response status codes

### PR DESCRIPTION
**Pull request by ericlin-nz**
This PR adds some of the missing response status codes that are present in the DICOM spec.

For reference, I looked at the pynetdicom [docs](https://pynetdicom2.readthedocs.io/en/latest/statuses.html ) to see which ones were missing. Please note that I've left out the statuses with verbose descriptions because I couldn't think of succinct names to associate each of them with.

### CODE REVIEW

**Comment by PantelisGeorgiadis** [comment]
Looks good and thank you for your contribution @ericlin-nz!

**Comment by richard-viney** [comment]
Thanks, could we cut a release with this in?

**Comment by PantelisGeorgiadis** [comment]
Sure Richard! Just give me a couple of days so I can release it along with a feature I'm working on.

**Comment by PantelisGeorgiadis** [comment]
Done!

**Pull request merged**
